apiVersion: v1
name: istio
version: 1.0.0
tillerVersion: ">=2.7.2"
description: Helm chart for deploying Istio by operator
keywords:
  - istio
  - operator
sources:
  - https://github.com/istio/istio/tree/master/operator
engine: gotpl
