apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  hub: {{.Values.hub}}
  tag: {{.Values.tag}}
  profile: empty

  meshConfig:
    accessLogFile: /dev/stdout
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    defaultConfig:
      proxyMetadata: {}
    enableAutoMtls: false
    enablePrometheusMerge: true

  # Traffic management feature
  components:
    base:
      enabled: true
    # Istio controlplane feature
    pilot:
      enabled: true
      k8s:
        # affinity:
        #   podAntiAffinity:
        #     requiredDuringSchedulingIgnoredDuringExecution:
        #     - labelSelector:
        #         matchExpressions:
        #         - key: istio
        #           operator: In
        #           values:
        #           - pilot
        #       topologyKey: kubernetes.io/hostname
        hpaSpec:
          maxReplicas: 5
          minReplicas: 2
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istiod
        # nodeSelector:
        #   worker-class: private
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 3
          timeoutSeconds: 5
            
    # Istio Gateway feature
    egressGateways:
    - name: istio-egressgateway
      enabled: true
      k8s:
        # affinity:
        #   podAntiAffinity:
        #     requiredDuringSchedulingIgnoredDuringExecution:
        #     - labelSelector:
        #         matchExpressions:
        #         - key: istio
        #           operator: In
        #           values:
        #           - egressgateway
        #       topologyKey: kubernetes.io/hostname
        # nodeSelector:
        #   worker-class: private-edge
        service:
          ports:
            - port: 80
              name: http2
              targetPort: 8080
              protocol: TCP
            - port: 443
              name: https
              targetPort: 8443
              protocol: TCP
            - port: 15443
              targetPort: 15443
              name: tls
              protocol: TCP
            - port: 3306
              name: mysql
              protocol: TCP
        hpaSpec:
          maxReplicas: 5
          minReplicas: 2
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-egressgateway

  values:
    global:
      istioNamespace: istio-system
      proxy:
        image: istio-proxyv2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        logLevel: info
        privileged: true
      proxy_init:
        image: istio-proxyv2
        resources:
          limits:
            cpu: 500m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi

    pilot:
      image: istio-pilot

    sidecarInjectorWebhook:
      enableNamespacesByDefault: true
      objectSelector:
        enabled: false

    clusterResources: true